<?php
    return [
        // Public Directory
        'ROOT' => env('ROOT'),
        // App Directory
        'APP_PATH' => env('APP_PATH'),
        // Classes Directory
        'CLASSES_PATH' => env('CLASS_PATH'),
        // Controllers Directory
        'CONTROLLER_PATH' => env('CONTROLLER_PATH'),
        // Exceptions Directory
        'EXCEPTIONS_PATH' => env('EXCEPTIONS_PATH'),
        // Models Directory
        'MODELS_PATH' => env('MODELS_PATH'),
        // Widgets Directory
        'WIDGETS_PATH' => env('WIDGETS_PATH'),
        // Config Directory
        'CONFIG_PATH' => env('CONFIG_PATH'),
        // Framework Directory
        'FRAMEWORK_PATH' => env('FRAMEWORK_PATH'),
        // Blade Directory
        'BLADE_PATH' => env('BLADE_PATH'),
        // Core Directory
        'CORE_PATH' => env('CORE_PATH'),
        // Helpers Directory
        'HELPER_PATH' => env('HELPER_PATH'),
        // Libraries Directory
        'LIB_PATH' => env('LIB_PATH'),
        // Routes Directory
        'ROUTES_PATH' => env('ROUTE_PATH'),
        // Logs Directory
        'LOGS_PATH' => env('LOGS_PATH'),
        // Cache Directory
        'CACHE_PATH' => env('CACHE_PATH'),
        // Resources Directory
        'RESOURCES_PATH' => env('RESOURCES_PATH'),
        // Themes Directory
        'THEMES_PATH' => env('THEMES_PATH'),
        // Core Theme Directory
        'CORE_THEME_PATH' => env('CORE_THEME_PATH'),
        // Ajax Directory
        'AJAX_PATH' => env('AJAX_PATH'),
        // Languages Directory
        'LANGS_PATH' => env('LANGS_PATH'),
        // Views Directory
        'VIEWS_PATH' => env('VIEWS_PATH'),
        // URL Root
        'URL_ROOT' => 'http://shaiyabattles.local',
    ];
